### ISSUE TITLE
When i Use DateTimePickerDialog, it crashed

### ISSUE THREAD

**Issue by kapaseker** [OfficeDev/ui-fabric-android#2]
2019-06-05 02:08:56.314 21201-21201/com.azalea.www.samplehub E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.azalea.www.samplehub, PID: 21201
    android.view.InflateException: Binary XML file line #16: com.microsoft.officeuifabric.datetimepicker.DateTimePicker$onTabSelectedListener$1 cannot be cast to com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener
    Caused by: java.lang.ClassCastException: com.microsoft.officeuifabric.datetimepicker.DateTimePicker$onTabSelectedListener$1 cannot be cast to com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener
        at com.microsoft.officeuifabric.datetimepicker.DateTimePicker.onFinishInflate(DateTimePicker.kt:160)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.microsoft.officeuifabric.datetimepicker.DateTimePickerFragment.onCreateView(DateTimePickerFragment.kt:48)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1686)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:230)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at com.microsoft.officeuifabric.view.WrapContentViewPager.onMeasure(WrapContentViewPager.kt:101)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:690)
2019-06-05 02:08:56.314 21201-21201/com.azalea.www.samplehub E/AndroidRuntime:     at android.view.View.measure(View.java:19857)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1339)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6169)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

i add andoridX support ,not andorid.support。but if this project can run with kotlin, please migrate to androidX

**Comment by williamado** [comment]
I built a quick test app using AndroidX and was unable to reproduce this crash. 

Looking into the cast error, I found this thread: https://github.com/JakeWharton/RxBinding/issues/495

I was able to repro the crash when implementing an alpha version of Material Components. Would you happen to be using 1.1.0-alpha* version?

**Comment by kapaseker** [comment]
this is my androidX dependencies:

    implementation 'androidx.multidex:multidex:+'
    implementation 'androidx.multidex:multidex-instrumentation:+'
    implementation 'androidx.appcompat:appcompat:+'
    implementation 'com.google.android.material:material:+'
    implementation 'androidx.cardview:cardview:+'
    implementation 'com.android.support:support-dynamic-animation:+'
    implementation 'androidx.dynamicanimation:dynamicanimation:+'
    implementation 'androidx.constraintlayout:constraintlayout:+'
    implementation 'androidx.constraintlayout:constraintlayout-solver:+'

i add "+" , not a particular version， did you add 'com.android.support:design:28.0.0' denpendency ???
maybe i know the reason, the DateTimePickerDialog use a TabLayout of "android.support.design.widget.TabLayout" - this exist in com.android.support:design instead of the "com.google.android.material"

**Comment by kapaseker** [comment]
can i have your build.gradle file of app module? i just wanna see your dependencies

**Comment by williamado** [comment]
Here is my build.gradle file
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:exifinterface:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation project(':OfficeUIFabric-release-10')
    implementation 'com.google.android.material:material:1.1.0-alpha02'
    implementation 'com.jakewharton.threetenabp:threetenabp:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
I replaced the alpha version of material components with `com.google.android.material:material:+` and experienced the crash as well.

The stable release of material components `com.google.android.material:material:1.0.0` doesn't cause a crash. Can you use this version?

**Comment by kapaseker** [comment]
YES !!! it works ,thank you !!!

it's tough that manager third-part dependencies.

**Comment by williamado** [comment]
Yep, no worries! Glad this solution is working for you.
